version: "3.9"

services:
  react:
    build: .
    networks:
      - default
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env.development
    command: yarn start


networks:
  default:
    external: true
    name: server_default
