# Generated by Django 2.2.5 on 2019-11-09 20:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camper',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='camper_schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='lodging_schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='payment_schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
