# Generated by Django 3.0 on 2020-01-04 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0002_auto_20191109_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='lodging_schema',
            new_name='deposit_schema',
        ),
    ]
