# Generated by Django 3.0 on 2020-01-05 05:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0004_event_registration_ui_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='camper_pricing_logic',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='pricing',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_pricing_logic',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
