# Generated by Django 3.0.2 on 2020-02-01 20:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0005_auto_20200105_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camper',
            name='lodging',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='camphoric.Lodging'),
        ),
        migrations.AlterField(
            model_name='camper',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campers', to='camphoric.Registration'),
        ),
        migrations.AlterField(
            model_name='event',
            name='camper_pricing_logic',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='JsonLogic Camper-level pricing components', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='camper_schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='JSON schema for Camper.attributes', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='deposit_schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='JSON schema for Deposit.attributes', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='payment_schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='JSON schema for Payment.attributes', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='pricing',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='key-value object with pricing variables', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_pricing_logic',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='JsonLogic Registration-level pricing components', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='JSON schema for Registration.attributes', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_ui_schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='react-jsonschema-form uiSchema for registration form', null=True),
        ),
    ]
