# Generated by Django 3.0.2 on 2020-02-02 19:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0006_auto_20200201_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='client_pricing_results',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='server_pricing_results',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
