# Generated by Django 3.0.2 on 2020-02-14 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0007_auto_20200202_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='client_pricing_results',
            new_name='client_reported_pricing',
        ),
    ]
