# Generated by Django 3.0.3 on 2020-02-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0008_auto_20200214_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='registrant_email',
            field=models.EmailField(default='test@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
