# Generated by Django 3.0.3 on 2020-02-23 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0009_registration_registrant_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='confirmation_email_body',
            field=models.TextField(default='', help_text='will be passed through str.format'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='confirmation_email_from',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='confirmation_email_subject',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='confirmation_page_html',
            field=models.TextField(default='', help_text='will be passed through str.format'),
            preserve_default=False,
        ),
    ]
