# Generated by Django 3.0.3 on 2020-02-23 19:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0010_auto_20200223_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='confirmation_email_body',
        ),
        migrations.RemoveField(
            model_name='event',
            name='confirmation_page_html',
        ),
        migrations.AddField(
            model_name='event',
            name='confirmation_email_template',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[], help_text='JsonLogic template'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='confirmation_page_template',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[], help_text='JsonLogic template'),
            preserve_default=False,
        ),
    ]
