# Generated by Django 3.0.3 on 2020-05-30 16:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0011_auto_20200223_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='confirmation_email_subject',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='confirmation_email_template',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, help_text='JsonLogic template'),
        ),
        migrations.AlterField(
            model_name='event',
            name='confirmation_page_template',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, help_text='JsonLogic template'),
        ),
    ]
