# Generated by Django 3.0.3 on 2020-10-24 23:53

import camphoric.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0012_auto_20200530_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(help_text='value exposed to JsonLogic', max_length=255)),
                ('label', models.CharField(help_text='Human readable name', max_length=255)),
                ('invitation_email_template', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camphoric.Event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('invitation_code', models.CharField(default=camphoric.models.Invitation.invitation_code_default, max_length=8)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('sent_time', models.DateTimeField(null=True)),
                ('expiration_time', models.DateTimeField(null=True)),
                ('registration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='camphoric.Registration')),
                ('registration_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camphoric.RegistrationType')),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='registration_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='camphoric.RegistrationType'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(fields=('invitation_code', 'recipient_email'), name='email_invitation_code'),
        ),
    ]
