# Generated by Django 3.1.5 on 2021-01-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0016_auto_20210117_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationtype',
            name='invitation_email_subject',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
