# Generated by Django 3.1.5 on 2021-01-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0017_registrationtype_invitation_email_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
