# Generated by Django 3.1.5 on 2021-01-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0018_invitation_recipient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='confirmation_email_template',
            field=models.TextField(blank=True, default='', help_text='Mustache template'),
        ),
        migrations.AlterField(
            model_name='event',
            name='confirmation_page_template',
            field=models.TextField(blank=True, default='', help_text='Mustache template'),
        ),
    ]
