# Generated by Django 3.2.8 on 2021-11-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0019_auto_20210123_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodging',
            name='reserved',
            field=models.IntegerField(default=0, help_text='number of reserved spots remaining'),
        ),
        migrations.AddField(
            model_name='lodging',
            name='visible',
            field=models.BooleanField(default=False, help_text='true if visible on registration form'),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='capacity',
            field=models.IntegerField(default=0, help_text='total camper capacity'),
        ),
    ]
