# Generated by Django 3.2.8 on 2021-11-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0020_auto_20211107_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodging',
            name='children_title',
            field=models.CharField(blank=True, default='', help_text='title that goes on the dropdown field to select a child', max_length=255),
        ),
    ]
