# Generated by Django 3.2.8 on 2021-11-19 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0021_lodging_children_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='confirmation_email_template',
            field=models.TextField(blank=True, default='', help_text='Handlebars template'),
        ),
        migrations.AlterField(
            model_name='event',
            name='confirmation_page_template',
            field=models.TextField(blank=True, default='', help_text='Handlebars template'),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('title', models.CharField(max_length=255)),
                ('template', models.TextField(blank=True, default='', help_text='Handlebars template')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camphoric.event')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
