# Generated by Django 3.2.9 on 2021-12-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0022_auto_20211119_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='camper_pricing_logic',
            field=models.JSONField(default=dict, help_text='JsonLogic Camper-level pricing components'),
        ),
        migrations.AlterField(
            model_name='event',
            name='camper_schema',
            field=models.JSONField(default=dict, help_text='JSON schema for Camper.attributes'),
        ),
        migrations.AlterField(
            model_name='event',
            name='confirmation_email_from',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='event',
            name='confirmation_email_subject',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='deposit_schema',
            field=models.JSONField(default=dict, help_text='JSON schema for Deposit.attributes'),
        ),
        migrations.AlterField(
            model_name='event',
            name='payment_schema',
            field=models.JSONField(default=dict, help_text='JSON schema for Payment.attributes'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pricing',
            field=models.JSONField(default=dict, help_text='key-value object with pricing variables'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_pricing_logic',
            field=models.JSONField(default=dict, help_text='JsonLogic Registration-level pricing components'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_schema',
            field=models.JSONField(default=dict, help_text='JSON schema for Registration.attributes'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_ui_schema',
            field=models.JSONField(default=dict, help_text='react-jsonschema-form uiSchema for registration form'),
        ),
    ]
