# Generated by Django 3.2.9 on 2021-12-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0023_auto_20211223_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='camper',
            name='lodging_reserved',
            field=models.BooleanField(default=False, help_text='true if this camper is assigned to a reserved lodging spot'),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='reserved',
            field=models.IntegerField(default=0, help_text='number of reserved spots'),
        ),
    ]
