# Generated by Django 3.2.12 on 2022-06-26 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0026_auto_20220123_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(help_text='A unique name for this account', max_length=255)),
                ('backend', models.CharField(choices=[('django.core.mail.backends.smtp.EmailBackend', 'SMTP'), ('django.core.mail.backends.console.EmailBackend', 'Console')], default='django.core.mail.backends.smtp.EmailBackend', help_text='the Django email backend to use', max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField()),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camphoric.organization')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='email_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='camphoric.emailaccount'),
        ),
        migrations.AddConstraint(
            model_name='emailaccount',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='email_account_name'),
        ),
    ]
