# Generated by Django 3.2.12 on 2022-08-23 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0027_auto_20220626_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('Check', 'Check'), ('PayPal', 'PayPal')], default='Check', max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='deposit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='camphoric.deposit'),
        ),
    ]
