# Generated by Django 3.2.12 on 2022-08-27 04:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0028_auto_20220823_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='paypal_client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='paypal_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_type',
            field=models.CharField(choices=[('Check', 'Check'), ('PayPal', 'PayPal')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='paypal_response',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
