# Generated by Django 3.2.15 on 2022-08-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0029_auto_20220827_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paypal_order_details',
            field=models.JSONField(null=True),
        ),
    ]
