# Generated by Django 3.2.15 on 2022-09-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0030_payment_paypal_order_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pre_submit_template',
            field=models.TextField(blank=True, default='', help_text='Handlebars template, rendered right before registration submit button'),
        ),
    ]
