# Generated by Django 3.2.15 on 2022-09-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0031_event_pre_submit_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('Check', 'Check'), ('PayPal', 'PayPal'), ('Card', 'Debit or Credit Card')], default='Check', max_length=255),
        ),
        migrations.AlterField(
            model_name='registration',
            name='payment_type',
            field=models.CharField(choices=[('Check', 'Check'), ('PayPal', 'PayPal'), ('Card', 'Debit or Credit Card')], max_length=255, null=True),
        ),
    ]
