# Generated by Django 3.2.15 on 2022-09-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0032_auto_20220906_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='camper',
            name='stay_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='camper',
            name='stay_start',
            field=models.DateField(null=True),
        ),
    ]
