# Generated by Django 3.2.15 on 2022-09-14 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0033_auto_20220914_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='deposited_on',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_on',
            field=models.DateField(null=True),
        ),
    ]
