# Generated by Django 3.2.15 on 2022-09-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0034_auto_20220914_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='default_stay_length',
            field=models.SmallIntegerField(default=1, help_text='The number of days that a camper stays by default'),
        ),
    ]
