# Generated by Django 3.2.15 on 2022-09-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0037_camper_lodging_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('Check', 'Check'), ('PayPal', 'PayPal'), ('Card', 'Debit or Credit Card'), ('Voucher', 'Discount or Gifted Credit')], default='Check', max_length=255),
        ),
        migrations.AlterField(
            model_name='registration',
            name='payment_type',
            field=models.CharField(choices=[('Check', 'Check'), ('PayPal', 'PayPal'), ('Card', 'Debit or Credit Card'), ('Voucher', 'Discount or Gifted Credit')], max_length=255, null=True),
        ),
    ]
