# Generated by Django 4.1.4 on 2022-12-11 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0039_camper_lodging_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkEmailTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('from_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('body_template', models.TextField(blank=True, default='', help_text='Handlebars Markdown template')),
                ('running_pid', models.IntegerField(help_text='PID of process running the task, None if not running', null=True)),
                ('run_uuid', models.UUIDField(help_text='unique ID for most recent run', null=True)),
                ('run_start_time', models.DateTimeField(help_text='start time of most recent run', null=True)),
                ('run_finish_time', models.DateTimeField(help_text='finish time of most recent run', null=True)),
                ('error', models.CharField(blank=True, max_length=255, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camphoric.event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BulkEmailRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('sent_time', models.DateTimeField(null=True)),
                ('error', models.CharField(blank=True, max_length=255, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='camphoric.bulkemailtask')),
            ],
        ),
        migrations.AddConstraint(
            model_name='bulkemailrecipient',
            constraint=models.UniqueConstraint(fields=('task', 'email'), name='task_email'),
        ),
    ]
