# Generated by Django 4.1.4 on 2022-12-17 19:11

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0040_bulkemailtask_bulkemailrecipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkemailtask',
            name='messages_per_second',
            field=models.DecimalField(decimal_places=3, help_text='Max number of messages to send per second', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
    ]
