# Generated by Django 4.1.4 on 2023-02-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0041_bulkemailtask_messages_per_second'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_template_vars',
            field=models.JSONField(default=dict, help_text='variables to be used on the registration page descriptions'),
        ),
    ]
