# Generated by Django 4.1.4 on 2023-02-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0042_event_registration_template_vars'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_deposit_schema',
            field=models.JSONField(help_text='variables to be used on the registration page deposits', null=True),
        ),
    ]
