# Generated by Django 4.1.4 on 2023-02-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0043_event_registration_deposit_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='initial_payment',
            field=models.JSONField(null=True),
        ),
    ]
