# Generated by Django 4.1.4 on 2023-03-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0044_registration_initial_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='completed',
            field=models.BooleanField(default=False, help_text='True if the user has made it to the end of the registration process'),
        ),
    ]
