# Generated by Django 4.2.1 on 2023-06-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0046_populate_registration_completed_20230315_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='camper',
            name='admin_attributes',
            field=models.JSONField(default=dict, help_text='custom attributes for administrative use'),
        ),
        migrations.AddField(
            model_name='event',
            name='camper_admin_schema',
            field=models.JSONField(default=dict, help_text='JSON schema for Camper.admin_attributes'),
        ),
    ]
