# Generated by Django 4.2.1 on 2023-07-07 02:27

from django.db import migrations, models


def add_report_type(apps, schema_editor):
    Report = apps.get_model('camphoric', 'Report')
    for report in Report.objects.all():
        report.output = 'hbs'
        report.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0048_camper_server_pricing_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='output',
            field=models.CharField(choices=[('html', 'Jinja to HTML'), ('md', 'Jinja to Markdown'), ('csv', 'Jinja to CSV'), ('hbs', 'Handlebars to Markdown'), ('txt', 'Jinja to Plain Text')], default='md', max_length=4),
        ),
        migrations.AddField(
            model_name='report',
            name='variables_schema',
            field=models.JSONField(default=dict, help_text='values schema for this reports variables'),
        ),
        migrations.RunPython(add_report_type, backwards),
    ]
