# Generated by Django 4.2.3 on 2025-01-03 02:39

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0050_alter_camper_options_camper_sequence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomChargeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('label', models.CharField(help_text='human friendly name', max_length=255)),
                ('name', models.CharField(help_text='machine name', max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camphoric.event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('notes', models.TextField(blank=True, default='')),
                ('camper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camphoric.camper')),
                ('custom_charge_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camphoric.customchargetype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
