# Generated by Django 4.2.3 on 2026-01-31 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0051_customchargetype_customcharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='epayment_handling',
            field=models.DecimalField(
                null=True,
                max_digits=4,
                decimal_places=2,
                help_text="a handling charge added to all payments, but discounted if you pay by check"
            ),
        ),
    ]
