# Generated by Django 4.2.3 on 2026-01-31 08:49

import camphoric.models
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0052_event_epayment_handling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camper',
            name='admin_attributes',
            field=camphoric.models.CustomJSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='custom attributes for administrative use'),
        ),
        migrations.AlterField(
            model_name='camper',
            name='attributes',
            field=camphoric.models.CustomJSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='camper',
            name='server_pricing_results',
            field=camphoric.models.CustomJSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='camper',
            name='stay',
            field=camphoric.models.CustomJSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='JSON array of dates', null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='attributes',
            field=camphoric.models.CustomJSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='camper_admin_schema',
            field=camphoric.models.CustomJSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='JSON schema for Camper.admin_attributes'),
        ),
        migrations.AlterField(
            model_name='event',
            name='camper_pricing_logic',
            field=camphoric.models.CustomJSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='JsonLogic Camper-level pricing components'),
        ),
        migrations.AlterField(
            model_name='event',
            name='camper_schema',
            field=camphoric.models.CustomJSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='JSON schema for Camper.attributes'),
        ),
        migrations.AlterField(
            model_name='event',
            name='deposit_schema',
            field=camphoric.models.CustomJSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='JSON schema for Deposit.attributes'),
        ),
        migrations.AlterField(
            model_name='event',
            name='payment_schema',
            field=camphoric.models.CustomJSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='JSON schema for Payment.attributes'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pricing',
            field=camphoric.models.CustomJSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='key-value object with pricing variables'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_admin_schema',
            field=camphoric.models.CustomJSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='JSON schema for Registration.admin_attributes'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_deposit_schema',
            field=camphoric.models.CustomJSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='variables to be used on the registration page deposits', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_pricing_logic',
            field=camphoric.models.CustomJSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='JsonLogic Registration-level pricing components'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_schema',
            field=camphoric.models.CustomJSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='JSON schema for Registration.attributes'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_template_vars',
            field=camphoric.models.CustomJSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='variables to be used on the registration page descriptions'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_ui_schema',
            field=camphoric.models.CustomJSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='react-jsonschema-form uiSchema for registration form'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='attributes',
            field=camphoric.models.CustomJSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paypal_order_details',
            field=camphoric.models.CustomJSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='admin_attributes',
            field=camphoric.models.CustomJSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='custom attributes for administrative use'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='attributes',
            field=camphoric.models.CustomJSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='client_reported_pricing',
            field=camphoric.models.CustomJSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='initial_payment',
            field=camphoric.models.CustomJSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='paypal_response',
            field=camphoric.models.CustomJSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='server_pricing_results',
            field=camphoric.models.CustomJSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='variables_schema',
            field=camphoric.models.CustomJSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='values schema for this reports variables'),
        ),
    ]
