# Generated by Django 4.2.3 on 2026-02-03 00:24

import camphoric.models
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0053_alter_camper_admin_attributes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationtype',
            name='camper_schema_overrides',
            field=camphoric.models.CustomJSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='JSON schema for overriding camper schema items'),
        ),
        migrations.AddField(
            model_name='registrationtype',
            name='registration_schema_overrides',
            field=camphoric.models.CustomJSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='JSON schema for overriding registration schema items'),
        ),
        migrations.AddField(
            model_name='registrationtype',
            name='ui_schema_overrides',
            field=camphoric.models.CustomJSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='JSON schema for overriding camper schema items'),
        ),
    ]
