# Generated by Django 4.2.27 on 2026-09-24 21:31

import camphoric.models
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0055_payment_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_error_messages',
            field=camphoric.models.CustomJSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text="Custom validation messages for the registration form: { field path: { validation keyword: Handlebars message } }, where array indexes in the path are written as '*' and the path '*' holds event-wide defaults per keyword"),
        ),
    ]
