# Generated by Django 4.2.27 on 2026-09-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0056_event_registration_error_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='variables_source',
            field=models.CharField(choices=[('client', 'Client bundle (legacy)'), ('server', 'Camphoric variables')], default='client', help_text="Where the template's variables come from", max_length=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='template',
            field=models.TextField(blank=True, default='', help_text='Jinja or Handlebars template'),
        ),
    ]
