# Generated by Django 4.2.27 on 2026-09-25 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0057_report_variables_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='confirmation_email_engine',
            field=models.CharField(choices=[('mustache', 'Mustache (legacy)'), ('jinja', 'Jinja (Camphoric variables)')], default='mustache', help_text="How the confirmation email's subject and body are written", max_length=10),
        ),
        migrations.AddField(
            model_name='registrationtype',
            name='invitation_email_engine',
            field=models.CharField(choices=[('mustache', 'Mustache (legacy)'), ('jinja', 'Jinja (Camphoric variables)')], default='mustache', help_text="How the invitation email's subject and body are written", max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='confirmation_email_template',
            field=models.TextField(blank=True, default='', help_text='Mustache or Jinja template (see the engine)'),
        ),
    ]
