# Generated by Django 4.2.27 on 2026-09-25 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0058_email_template_engines'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkemailrecipient',
            name='camper',
            field=models.ForeignKey(blank=True, help_text='The camper this copy is about (camper lists)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='camphoric.camper'),
        ),
        migrations.AddField(
            model_name='bulkemailrecipient',
            name='registration',
            field=models.ForeignKey(blank=True, help_text='The registration this copy is about (registration and camper lists)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='camphoric.registration'),
        ),
        migrations.AddField(
            model_name='bulkemailtask',
            name='address_expression',
            field=models.TextField(blank=True, default='', help_text="Jinja expression for each recipient's address; blank uses the default"),
        ),
        migrations.AddField(
            model_name='bulkemailtask',
            name='engine',
            field=models.CharField(choices=[('mustache', 'Mustache (legacy)'), ('jinja', 'Jinja (Camphoric variables)')], default='mustache', help_text='How the subject and body are written; Mustache sees only `recipient`', max_length=10),
        ),
        migrations.AddField(
            model_name='bulkemailtask',
            name='include_incomplete',
            field=models.BooleanField(default=False, help_text="Also choose from registrations that weren't completed"),
        ),
        migrations.AddField(
            model_name='bulkemailtask',
            name='name_expression',
            field=models.TextField(blank=True, default='', help_text="Jinja expression for each recipient's name; blank uses the default"),
        ),
        migrations.AddField(
            model_name='bulkemailtask',
            name='recipient_filter',
            field=models.TextField(blank=True, default='', help_text='Jinja expression choosing registrations/campers; blank chooses all'),
        ),
        migrations.AddField(
            model_name='bulkemailtask',
            name='recipient_kind',
            field=models.CharField(choices=[('manual', 'Listed addresses'), ('registrations', 'Registrations'), ('campers', 'Campers')], default='manual', help_text='What the recipient list is built from', max_length=16),
        ),
        migrations.AddField(
            model_name='bulkemailtask',
            name='recipient_list',
            field=models.TextField(blank=True, default='', help_text='Listed addresses, one per line: `email` or `Name <email>`'),
        ),
        migrations.AlterField(
            model_name='bulkemailtask',
            name='body_template',
            field=models.TextField(blank=True, default='', help_text="Markdown template, in the task's engine"),
        ),
        migrations.AlterField(
            model_name='bulkemailtask',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
