# Generated by Django 4.2.27 on 2026-09-25 04:04

'''
New email templates default to Jinja, and new reports to the server's
variables (DR-40). Only the defaults change: existing rows keep the engine
and variables source they were saved with.
'''

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0059_bulk_email_recipients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkemailtask',
            name='engine',
            field=models.CharField(choices=[('mustache', 'Mustache (legacy)'), ('jinja', 'Jinja (Camphoric variables)')], default='jinja', help_text='How the subject and body are written; Mustache sees only `recipient`', max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='confirmation_email_engine',
            field=models.CharField(choices=[('mustache', 'Mustache (legacy)'), ('jinja', 'Jinja (Camphoric variables)')], default='jinja', help_text="How the confirmation email's subject and body are written", max_length=10),
        ),
        migrations.AlterField(
            model_name='registrationtype',
            name='invitation_email_engine',
            field=models.CharField(choices=[('mustache', 'Mustache (legacy)'), ('jinja', 'Jinja (Camphoric variables)')], default='jinja', help_text="How the invitation email's subject and body are written", max_length=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='variables_source',
            field=models.CharField(choices=[('client', 'Client bundle (legacy)'), ('server', 'Camphoric variables')], default='server', help_text="Where the template's variables come from", max_length=10),
        ),
    ]
