# Generated by Django 4.2.27 on 2026-09-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0060_jinja_and_server_variables_by_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='confirmation_page_template',
            field=models.TextField(blank=True, default='', help_text='Jinja markdown template, rendered on the server when registration completes'),
        ),
    ]
