# Generated by Django 6.1.1 on 2026-09-25 23:40

import camphoric.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from camphoric import crypto


def encrypt_passwords(apps, schema_editor):
    # Raw SQL: the historical model's field would encrypt again on save.
    with schema_editor.connection.cursor() as cursor:
        cursor.execute('SELECT id, password FROM camphoric_emailaccount')
        for account_id, password in cursor.fetchall():
            if password and not crypto.is_encrypted(password):
                cursor.execute('UPDATE camphoric_emailaccount SET password = %s WHERE id = %s',
                               [crypto.encrypt(password), account_id])


def decrypt_passwords(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute('SELECT id, password FROM camphoric_emailaccount')
        for account_id, password in cursor.fetchall():
            if crypto.is_encrypted(password):
                cursor.execute('UPDATE camphoric_emailaccount SET password = %s WHERE id = %s',
                               [crypto.decrypt(password)[:255], account_id])


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0061_confirmation_page_jinja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='default_reply_to',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='max_per_day',
            field=models.PositiveIntegerField(blank=True, help_text='Most messages to send in any 24 hours (blank: no limit). Gmail allows about 500 for personal accounts and 2,000 for Workspace.', null=True),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='max_per_minute',
            field=models.PositiveIntegerField(blank=True, help_text='Most messages to send in any minute (blank: no limit)', null=True),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='security',
            field=models.CharField(choices=[('starttls', 'STARTTLS (usually port 587)'), ('ssl', 'SSL/TLS (usually port 465)'), ('none', 'None')], default='starttls', max_length=10),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='timeout',
            field=models.PositiveIntegerField(default=30, help_text='Seconds to wait for the server'),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='password',
            field=camphoric.models.EncryptedTextField(blank=True, help_text='Stored encrypted'),
        ),
        migrations.RunPython(encrypt_passwords, decrypt_passwords),
        migrations.AlterField(
            model_name='emailaccount',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='email_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='camphoric.emailaccount'),
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('kind', models.CharField(choices=[('confirmation', 'Registration confirmation'), ('confirmation_report', 'Confirmation email problem report'), ('page_report', 'Confirmation page problem report'), ('invitation', 'Invitation'), ('bulk', 'Bulk email'), ('test', 'Test email')], max_length=30)),
                ('from_email', models.CharField(max_length=255)),
                ('to', models.CharField(max_length=255)),
                ('reply_to', models.CharField(blank=True, max_length=255)),
                ('subject', models.TextField()),
                ('text', models.TextField()),
                ('html', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=10)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('smtp_message_id', models.CharField(blank=True, max_length=255)),
                ('dedupe_key', models.CharField(blank=True, max_length=255, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='camphoric.emailaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_messages', to='camphoric.event')),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='camphoric.invitation')),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='camphoric.registration')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='email_message_due'), models.Index(fields=['account', 'sent_at'], name='email_message_account_sent'), models.Index(fields=['event', '-created_at'], name='email_message_event_recent')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dedupe_key__isnull', False), models.Q(('status', 'cancelled'), _negated=True)), fields=('dedupe_key',), name='email_message_dedupe_key')],
            },
        ),
    ]
