# Generated by Django 6.1.1 on 2026-09-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0062_email_outbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerHeartbeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.CharField(max_length=64, unique=True)),
                ('hostname', models.CharField(max_length=255)),
                ('pid', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField()),
                ('seen_at', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
