# Generated by Django 6.1.1 on 2026-09-26 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0063_worker_heartbeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_messages', to='camphoric.event'),
        ),
    ]
