# Generated by Django 6.1.1 on 2026-09-26 05:58

import django.db.models.deletion
from django.db import migrations, models

from camphoric.templating import mustache

JINJA = 'jinja'


def _jinja(text, subject, engine, shapes, where):
    '''The subject and body in Jinja: converted from Mustache, or as they were.'''
    if engine == JINJA:
        return subject or '', text or ''
    try:
        return (mustache.convert(subject or '', shapes), mustache.convert(text or '', shapes))
    except mustache.MustacheConversionError as error:
        # Keep the text and say so; the template checks will show what's wrong.
        print(f'\n  {where}: not converted from Mustache ({error}); check this template')
        note = f"{{# Couldn't be converted from Mustache automatically ({error}); check it. #}}\n"
        return subject or '', note + (text or '')


def move_email_templates(apps, schema_editor):
    '''
    Every event's confirmation email and every registration type's invitation
    become email templates, converted to Jinja if they were Mustache (DR-45).
    '''
    Event = apps.get_model('camphoric', 'Event')
    RegistrationType = apps.get_model('camphoric', 'RegistrationType')
    EmailTemplate = apps.get_model('camphoric', 'EmailTemplate')
    for event in Event.objects.all():
        shapes = mustache.confirmation_shapes(event.registration_schema, event.camper_schema)
        subject, body = _jinja(event.confirmation_email_template,
                               event.confirmation_email_subject,
                               event.confirmation_email_engine, shapes,
                               f'{event.name}: confirmation email')
        event.confirmation_template = EmailTemplate.objects.create(
            event=event, purpose='confirmation', name='Registration confirmation',
            subject=subject, body=body)
        event.save(update_fields=['confirmation_template'])
    for registration_type in RegistrationType.objects.select_related('event'):
        subject, body = _jinja(registration_type.invitation_email_template,
                               registration_type.invitation_email_subject,
                               registration_type.invitation_email_engine,
                               mustache.invitation_shapes(),
                               f'{registration_type.event.name}: {registration_type.label} '
                               'invitation')
        registration_type.invitation_template = EmailTemplate.objects.create(
            event=registration_type.event, purpose='invitation',
            name=f'Invitation: {registration_type.label}', subject=subject, body=body)
        registration_type.save(update_fields=['invitation_template'])


def restore_email_fields(apps, schema_editor):
    '''Going back: the templates' (Jinja) text returns to the old fields.'''
    Event = apps.get_model('camphoric', 'Event')
    RegistrationType = apps.get_model('camphoric', 'RegistrationType')
    for event in Event.objects.exclude(confirmation_template=None).select_related(
            'confirmation_template'):
        event.confirmation_email_subject = event.confirmation_template.subject[:100]
        event.confirmation_email_template = event.confirmation_template.body
        event.confirmation_email_engine = JINJA
        event.save()
    for registration_type in RegistrationType.objects.exclude(
            invitation_template=None).select_related('invitation_template'):
        registration_type.invitation_email_subject = registration_type.invitation_template.subject
        registration_type.invitation_email_template = registration_type.invitation_template.body
        registration_type.invitation_email_engine = JINJA
        registration_type.save()


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0064_email_message_without_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('purpose', models.CharField(choices=[('confirmation', 'Registration confirmation'), ('invitation', 'Invitation'), ('group', 'Group email')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='', help_text='Jinja markdown')),
                ('from_email', models.CharField(blank=True, default='', help_text="The sender; blank: the event's confirmation_email_from", max_length=255)),
                ('reply_to', models.CharField(blank=True, default='', help_text="Where replies go; blank: the sending account's default", max_length=255)),
                ('account', models.ForeignKey(blank=True, help_text="The sending account; blank: the event's", null=True, on_delete=django.db.models.deletion.SET_NULL, to='camphoric.emailaccount')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='camphoric.event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='confirmation_template',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='camphoric.emailtemplate'),
        ),
        migrations.AddField(
            model_name='registrationtype',
            name='invitation_template',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='camphoric.emailtemplate'),
        ),
        migrations.RunPython(move_email_templates, restore_email_fields),
        migrations.RemoveField(
            model_name='event',
            name='confirmation_email_engine',
        ),
        migrations.RemoveField(
            model_name='event',
            name='confirmation_email_subject',
        ),
        migrations.RemoveField(
            model_name='event',
            name='confirmation_email_template',
        ),
        migrations.RemoveField(
            model_name='registrationtype',
            name='invitation_email_engine',
        ),
        migrations.RemoveField(
            model_name='registrationtype',
            name='invitation_email_subject',
        ),
        migrations.RemoveField(
            model_name='registrationtype',
            name='invitation_email_template',
        ),
    ]
