# Generated by Django 6.1.1 on 2026-09-26 06:23

import camphoric.models
import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0065_email_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='recipient_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='camphoric.emailtemplate'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='address_expression',
            field=models.TextField(blank=True, default='', help_text="Jinja for each recipient's address; blank: default"),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='filter',
            field=camphoric.models.CustomJSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Rules choosing recipients: {combinator, rules: [{field, op, value}]}'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='filter_expression',
            field=models.TextField(blank=True, default='', help_text='A Jinja expression recipients must also pass'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='include_incomplete',
            field=models.BooleanField(default=False, help_text="Also choose from registrations that weren't completed"),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='name_expression',
            field=models.TextField(blank=True, default='', help_text="Jinja for each recipient's name; blank: default"),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='recipient_list',
            field=models.TextField(blank=True, default='', help_text='Listed addresses, one per line: email or Name <email>'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='recipient_source',
            field=models.CharField(choices=[('registrations', 'Registrations'), ('campers', 'Campers'), ('manual', 'Listed addresses')], default='registrations', max_length=16),
        ),
        migrations.CreateModel(
            name='EmailBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(help_text="The template's name when it was sent", max_length=255)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('recipient_source', models.CharField(choices=[('registrations', 'Registrations'), ('campers', 'Campers'), ('manual', 'Listed addresses')], max_length=16)),
                ('address_expression', models.TextField(blank=True, default='')),
                ('name_expression', models.TextField(blank=True, default='')),
                ('recipient_list', models.TextField(blank=True, default='')),
                ('recipient_keys', camphoric.models.CustomJSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('from_email', models.CharField(blank=True, default='', max_length=255)),
                ('reply_to', models.CharField(blank=True, default='', max_length=255)),
                ('skip_already_sent', models.BooleanField(default=True)),
                ('send_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('expanding', 'Preparing'), ('sending', 'Sending'), ('cancelled', 'Cancelled')], default='scheduled', max_length=10)),
                ('skipped', camphoric.models.CustomJSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('error', models.TextField(blank=True, default='')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='camphoric.emailaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_batches', to='camphoric.event')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='camphoric.emailtemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='camphoric.emailbatch'),
        ),
    ]
