# Generated by Django 6.1.1 on 2026-09-26 07:40

from django.db import migrations, models

# Task-based bulk email is replaced by group email templates (SPEC DR-45). Its
# tasks and recipients are dropped, not converted: the feature was never in a
# release, so only development databases hold any.


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0066_group_email'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bulkemailrecipient',
            name='task_email',
        ),
        migrations.RemoveField(
            model_name='bulkemailtask',
            name='event',
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='kind',
            field=models.CharField(choices=[('confirmation', 'Registration confirmation'), ('confirmation_report', 'Confirmation email problem report'), ('page_report', 'Confirmation page problem report'), ('invitation', 'Invitation'), ('bulk', 'Group email'), ('test', 'Test email')], max_length=30),
        ),
        migrations.DeleteModel(
            name='BulkEmailRecipient',
        ),
        migrations.DeleteModel(
            name='BulkEmailTask',
        ),
    ]
