# Generated by Django 6.1.1 on 2026-09-26 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0067_remove_bulk_email_tasks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailbatch',
            name='link_base',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='unsubscribe_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.CreateModel(
            name='EmailUnsubscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('email', models.EmailField(help_text='Lowercased', max_length=254)),
                ('source', models.CharField(choices=[('link', 'Unsubscribe link'), ('admin', 'Added by an organizer')], max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_unsubscribes', to='camphoric.event')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'email'), name='email_unsubscribe_address')],
            },
        ),
    ]
