# Generated by Django 6.1.1 on 2026-09-26 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0069_user_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='kind',
            field=models.CharField(choices=[('confirmation', 'Registration confirmation'), ('confirmation_report', 'Confirmation email problem report'), ('page_report', 'Confirmation page problem report'), ('invitation', 'Invitation'), ('bulk', 'Group email'), ('test', 'Test email'), ('account', 'Account email')], max_length=30),
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('must_change_password', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='camphoric_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
