# Generated by Django 6.1.1 on 2026-09-27 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0070_user_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camper',
            name='lodging',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='camphoric.lodging'),
        ),
        migrations.AlterField(
            model_name='camper',
            name='lodging_requested',
            field=models.ForeignKey(help_text='original lodging at time of registration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lodging_requested', to='camphoric.lodging'),
        ),
        migrations.AlterField(
            model_name='customcharge',
            name='custom_charge_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='camphoric.customchargetype'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='camphoric.organization'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='camphoric.registration'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='deposit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='camphoric.deposit'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='camphoric.registrationtype'),
        ),
    ]
