# Generated by Django 6.1.1 on 2026-09-27 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0071_delete_rules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('var', models.CharField(help_text="the pricing line's var", max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('reason', models.TextField()),
                ('camper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_overrides', to='camphoric.camper')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_overrides', to='camphoric.registration')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('camper__isnull', False)), fields=('camper', 'var'), name='one_override_per_camper_line'), models.UniqueConstraint(condition=models.Q(('camper__isnull', True)), fields=('registration', 'var'), name='one_override_per_registration_line')],
            },
        ),
    ]
