# Generated by Django 6.1.1 on 2026-09-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0072_pricing_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodging',
            name='availability',
            field=models.CharField(choices=[('auto', 'By capacity'), ('full', 'Always full'), ('open', 'Always open')], default='auto', help_text='whether registration offers it: by capacity, always full, or always open', max_length=4),
        ),
    ]
