# Generated by Django 6.1.1 on 2026-09-30 22:40

import camphoric.models
import django.core.serializers.json
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0073_lodging_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('label', models.CharField(help_text="human friendly name, shown on the discount's price line", max_length=255)),
                ('code', models.CharField(help_text='what the registrant enters', max_length=255)),
                ('pricing_logic', camphoric.models.CustomJSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='JsonLogic expression for the discount amount (a positive number)')),
                ('scope', models.CharField(choices=[('registration', 'Per registration'), ('camper', 'Per camper')], default='registration', help_text='whether the discount is worked out for the registration or for each camper', max_length=20)),
                ('enabled', models.BooleanField(default=True, help_text="False if registrants can't use this code")),
                ('expiration_date', models.DateTimeField(blank=True, help_text="registrants can't use this code after this time", null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='camphoric.event')),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='camphoric.promocode'),
        ),
        migrations.AddConstraint(
            model_name='promocode',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('event'), condition=models.Q(('deleted_at__isnull', True)), name='promo_code_per_event'),
        ),
    ]
