# Generated by Django 6.1.1 on 2026-10-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camphoric', '0079_registration_window_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='organizer_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
