#!/bin/bash

function usage() {
    cat <<EOF
Usage: $0 [-yf] [image-name]

This will PERMENANTLY delete images, volumes, and containers associated with
${PWD##*/}.  If you omit the optional image name, it will delete all of them.
EOF

}

while getopts yfh flag
do
    case "${flag}" in
        y) force=1;;
        f) force=1;;
        h) usage && exit 0;;
        [?]) echo >&2 "$(usage)" && exit 1;;
    esac
done

shift $((OPTIND-1)) # remove all flag arguments

if [ -z "$force" ]
then
    RED='\033[1;31m'
    NC='\033[0m' # No Color

    echo "$*"

    printf "${RED}WARNING: THIS CANNOT BE UNDONE${NC}\n"
    echo "This will delete all images, volumes, and containers associate with ${PWD##*/}"

    while true; do
        read -p "Do you wish to proceed [y/n]? " yn
        case $yn in
            [Yy]* ) break;;
            [Nn]* ) exit;;
            * ) echo "Please answer yes or no.";;
        esac
    done
fi

docker compose rm -sf $*
./remove-unused-docker-artifacts -f
