#!/bin/bash

function usage() {
    cat <<EOF
Usage: $0 [-yf]

This will PERMENANTLY delete ALL unused images and volumes.
EOF

}

while getopts yfh flag
do
    case "${flag}" in
        y) force=1;;
        f) force=1;;
        h) usage && exit 0;;
        [?]) echo >&2 "$(usage)" && exit 1;;
    esac
done

if [ -z "$force" ]
then
    RED='\033[1;31m'
    NC='\033[0m' # No Color
    
    printf "${RED}WARNING: THIS CANNOT BE UNDONE${NC}\n"
    echo "This will delete all unused images and volumes"
    
    while true; do
        read -p "Do you wish to proceed [y/n]? " yn
        case $yn in
            [Yy]* ) break;;
            [Nn]* ) exit;;
            * ) echo "Please answer yes or no.";;
        esac
    done
fi

docker image prune -af
docker volume prune -f
