#!/bin/bash

RED='\033[1;31m'
NC='\033[0m' # No Color

printf "${RED}WARNING: THIS CANNOT BE UNDONE${NC}\n"
echo "This will delete all images and volumes associate with ${PWD##*/}"

while true; do
    read -p "Do you wish to proceed [y/n]? " yn
    case $yn in
        [Yy]* ) break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done

docker-compose rm -sf
docker image prune -af
docker volume prune -f
