#!/bin/bash
cat <<EOF
helpful vagrant commands

Create, start and provision the vm
This also starts the django server at localhost:8000
  vagrant up

Run the ansible provisioner
  vagrant provision

Restart the VM
  vagrant reload

Show the state of the current VMs
  vagrant status

Run the data reset part of the provisioner
  ANSIBLE_ARGS='--tags camphoric_data_reset' vagrant provision

SSH into the vagrant machine
  vagrant ssh

Watch the django log files
  vagrant ssh -c "journalctl -f -u camphoric"

Run the frontend development server at localhost:3000
(NOTE: it is recommended that you run this locally, not in a VM.
This is because vite's watch-rebuild functionality won't work)
  vagrant ssh -c "cd /vagrant/client; npm start"

Run flake8
  vagrant ssh -c "cd /vagrant/server; pipenv run flake8"

Run django tests
  vagrant ssh -c "cd /vagrant/server; pipenv run ./manage.py test"

Destroy the VM
  vagrant destroy

EOF
