version: "3.9"

volumes:
    db:

services:
  postgres:
    image: postgres:13
    env_file:
      - .env/local/postgres
    ports:
      - "5434:5432"
    volumes:
      - db:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 3

  web:
    build: .
    env_file:
      - .env/local/django
    volumes:
      - ./camphoric:/app/camphoric
      - ./camphoric_server:/app/camphoric_server
      - ./frontend_bootstrap:/app/frontend_bootstrap
      - ./tests:/app/tests
      - ./setup.cfg:/app/setup.cfg
      - ./manage.py:/app/manage.py
      - ./.env:/app/.env
    command: >
      bash -c "./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy