#!/bin/bash

docker compose exec -T django python manage.py migrate
docker compose exec -T django python manage.py flush --noinput
docker compose exec -T django python manage.py createsuperuser --noinput
docker compose exec -T data import
docker compose exec -T data npx jest __tests__/lark.ts
