"""
Django settings for camphoric_server project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import environ
import mimetypes

mimetypes.add_type("text/css", ".css", True)
mimetypes.add_type("application/x-javascript", ".js", True)
mimetypes.add_type("image/jpeg", ".jpg", True)
mimetypes.add_type("image/jpeg", ".jpeg", True)

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

env = environ.Env(
    DEBUG=(bool, False)
)

# Read an optional .env file (server/.env by default; a missing file is skipped), so the
# same file works under any runner rather than relying on pipenv's auto-loading. Real
# environment variables take precedence over values from the file.
environ.Env.read_env(env.str('ENV_PATH', os.path.join(BASE_DIR, '.env')))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

# Application definition
INSTALLED_APPS = [
    'camphoric.apps.CamphoricConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'frontend_bootstrap',
    'dbbackup',  # django-dbbackup
    'django_filters',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves the collected static files (the built frontend) with DEBUG off, e.g. in the
    # container. django.conf.urls.static.static() is a no-op when DEBUG=False.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'camphoric_server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'camphoric_server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    # read os.environ['DATABASE_URL'] and raises ImproperlyConfigured exception if not found
    'default': env.db(),
}

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'


EMAIL_BACKEND = env('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = env('EMAIL_HOST', default=None)
EMAIL_PORT = env('EMAIL_PORT', default=None)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default=None)
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default=None)
EMAIL_USE_TLS = env('EMAIL_USE_TLS', default=True)
EMAIL_USE_SSL = env('EMAIL_USE_SSL', default=False)
EMAIL_TIMEOUT = env('EMAIL_TIMEOUT', default=30)


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/
# Figure out time represention naive vs aware

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

REACT_BUILD_DIR = os.path.join(BASE_DIR, "frontend_bootstrap/build")
REACT_STATIC_DIR = os.path.join(REACT_BUILD_DIR, 'static/')
REACT_STATIC_INDEX = os.path.join(REACT_BUILD_DIR, 'index.html')

# TODO: https://github.com/camphoric/camphoric/issues/185
STATIC_URL = 'static/'
MEDIA_URL = 'user_media/'
STATICFILES_DIRS = [
    REACT_STATIC_DIR,
]
# Absolute so collectstatic (and static serving) don't depend on the process CWD.
STATIC_ROOT = env.str('STATIC_ROOT', default=os.path.join(BASE_DIR, 'static'))

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    # Vite already content-hashes filenames, so plain compressed storage (not the
    # manifest variant) is enough for whitenoise to serve them cache-friendly.
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
    # django-dbbackup reads its storage from here (the legacy DBBACKUP_STORAGE /
    # DBBACKUP_STORAGE_OPTIONS settings are rejected), still driven by those env vars.
    # https://django-dbbackup.readthedocs.io/en/master/storage.html
    # An empty value (e.g. `DBBACKUP_STORAGE=` in a .env file) counts as unset.
    'dbbackup': {
        'BACKEND': (
            env.str('DBBACKUP_STORAGE', default='')
            or 'django.core.files.storage.FileSystemStorage'
        ),
        'OPTIONS': (
            env.json('DBBACKUP_STORAGE_OPTIONS', default={})
            or {'location': os.path.join(BASE_DIR, 'backup')}
        ),
    },
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
}

# The session cookie is Secure by default (production sits behind TLS; browsers exempt
# localhost). Set SESSION_COOKIE_SECURE=false for plain http on any other host. Behind a
# proxy that terminates TLS, set USE_X_FORWARDED_PROTO=true so Django sees requests as https.
SESSION_COOKIE_SECURE = env.bool('SESSION_COOKIE_SECURE', default=True)
CSRF_COOKIE_SECURE = env.bool('CSRF_COOKIE_SECURE', default=False)
if env.bool('USE_X_FORWARDED_PROTO', default=False):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

PAYPAL_BASE_URL = env('PAYPAL_BASE_URL')
PAYPAL_SECRET = env('PAYPAL_SECRET')

# Backups are configured under STORAGES['dbbackup'] above (env DBBACKUP_STORAGE_OPTIONS).

# Hosts and origins are comma-separated environment variables. The defaults cover local
# development: the Vite dev servers and the docker-compose "django" host.
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1', 'django'])
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[
    'https://localhost',
    'http://localhost:8000',
    'http://localhost:3000',
    'http://localhost:3001',
    'http://localhost:3002',
    'http://localhost:3003',
    'http://django:8000',
])
# Unused: django-cors-headers is not installed, so this setting has no effect. It is kept
# (env-driven) only because existing settings_override.py files assign it.
CORS_ORIGIN_WHITELIST = env.list('CORS_ORIGIN_WHITELIST', default=CSRF_TRUSTED_ORIGINS)

# Allow PayPal Popup
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'

# See http://docs.djangoproject.com/en/dev/topics/logging for
# more details on how to customize your logging configuration.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'logfile': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        # Unfiltered so requests are still logged when DEBUG is off (e.g. in a
        # container, where logs go to stdout). Verbose in development by default.
        'console': {
            'level': env.str('DJANGO_LOG_LEVEL', default='DEBUG' if DEBUG else 'INFO'),
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'mail_admins': {
            'level': 'ERROR',
            'formatter': 'verbose',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler',
        },
        # may be useful for production
        # 'applogfile': {
        #     'level': 'INFO',
        #     'formatter': 'logfile',
        #     'class': 'logging.handlers.RotatingFileHandler',
        #     'filters': ['require_debug_false'],
        #     'filename': os.path.join(BASE_DIR, 'camphoric.log'),
        #     'maxBytes': 1024*1024*15,  # 15MB
        #     'backupCount': 10,
        # },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
    # may be useful for production
    # 'loggers': {
    #     'django': {
    #         'handlers': ['applogfile'],
    #         'propagate': True,
    #     },
    # },
}
